from node:14-alpine
USER root


# COPY . /usr/src/app
COPY .npmrc .
COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .
COPY src .

RUN npm install typescript -g
RUN npm run build

CMD ["npm"  , "start"]