from node:14-alpine
USER root

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# COPY . /usr/src/app
# COPY .npmrc /usr/src/app
# COPY package.json /usr/src/app
# COPY package-lock.json /usr/src/app
# COPY tsconfig.json /usr/src/app
# COPY src /usr/src/app
COPY . /usr/src/app

RUN npm install typescript -g
RUN npm run build

EXPOSE 4000
CMD ["npm"  , "start"]